[project]
name = "autogen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncio>=4.0.0",
    "autogen-agentchat>=0.7.5",
    "autogen-ext[azure,openai]>=0.7.5",
    "dotenv>=0.9.9",
    "openai>=1.0.0",
    "pandas>=2.0.0",
    "plotly>=5.15.0",
    "pyarrow>=22.0.0",
    "requests>=2.31.0",
    "streamlit>=1.28.0",
]
